### ISSUE TITLE
routes.php not explained

### ISSUE THREAD

**Issue by slavkoss** [Viames/Pair_example#1]
As I understand (from parseCustomRoute fn) routes.php contains array of objects like this ? :
$this->routes = [
  // object how ??? : path, action, module ?
];
Example is needed how to handle scripts in \pair_user\modules\tevent
for my module created in Developer for table t_event :
\pair_user\modules\tevent

Example is needed : What with t_eventtype, t_event_eventtype ? 

CREATE TABLE t_eventtype(
  id      INT(10) NOT NULL,
  name    VARCHAR(255)
) ;

INSERT INTO t_eventtype (id, name) VALUES
 (1, 'PHP')
,(2, 'HTML, CSS')
,(3, 'JS')
,(4, 'My events')
;

CREATE TABLE t_event (
  id            int(10) NOT NULL,
  user_id       INT(10) DEFAULT NULL,
  title         varchar(255) DEFAULT NULL,
  summary       varchar(4096) DEFAULT NULL,
  estart        varchar(25) DEFAULT '0000-00-00 00:00:00',
  eend          varchar(25) DEFAULT '0000-00-00 00:00:00',
  elink          text,
  description1  text,
  description2  text,
  description3  text
) ;

CREATE TABLE t_event_eventtype (
  event_id INT(10) NOT NULL,
  eventtype_id INT(10) NOT NULL
) ;

ALTER TABLE t_eventtype ADD PRIMARY KEY (id);
ALTER TABLE t_eventtype MODIFY id int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE t_event ADD PRIMARY KEY (id);
ALTER TABLE t_event ADD KEY estart (estart);
ALTER TABLE t_event ADD FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE t_event MODIFY id int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE t_event_eventtype ADD PRIMARY KEY (event_id, eventtype_id);
ALTER TABLE t_event_eventtype ADD FOREIGN KEY (event_id) REFERENCES t_event (id);

**Comment by Viames** [comment]
Hi, I've just posted an update to [Pair](https://viames.github.io/Pair/) and [Pair_example](
https://github.com/viames/Pair_example). In the Pair_example project there are two new `routes.php` files. One is in the base directory at path, and can create fake modules, such as `groups`, which does not really exist.

The second one is at path `/modules/users/routes.php` and contains the routes for the `users` module. You will find many useful examples on the Wiki [Router](https://github.com/Viames/Pair/wiki/Router) page.

Btw, there is a problem in your query:
```sql
ALTER TABLE t_event ADD FOREIGN KEY (user_id) REFERENCES users (id);
```

In order to constrain to users table, the `t_event.user_id` field must be `INT(4) UNSIGNED`, otherwise MySQL refuses to create the foreign-key. Try changing your query to create the `t_event` table in this one:

```sql
CREATE TABLE t_event (
id int(10) NOT NULL,
user_id INT(4) UNSIGNED DEFAULT NULL,
title varchar(255) DEFAULT NULL,
summary varchar(4096) DEFAULT NULL,
estart varchar(25) DEFAULT '0000-00-00 00:00:00',
eend varchar(25) DEFAULT '0000-00-00 00:00:00',
elink text,
description1 text,
description2 text,
description3 text
);
```

Thank you for your contribution.
